version: '3'
services:
  app-debug:
    build:
      context: .
      dockerfile: ./env/app-debug/Dockerfile
    volumes:
      - ./:/app
      - ./env/app-debug/php.ini-development:/usr/local/etc/php/php.ini